server:
  port: 9110

dahua-server:
  ip: 13.65.33.11
  port: 8314
  username: zntk
  password: zntk12345

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://www.juxingtech.cn:3306/helmet?zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: root
    password: 123456
  mqtt:
    url: tcp://www.juxingtech.cn:1883
    username: admin
    password: public
    connectionTimeout: 30
    keepAliveInterval: 60
    completionTimeout: 30000
    defaultQos: 0
    pubClientId: ${random.value}  # 主题发送客户端ID
    subClientId: ${random.value}  # 订阅消息客户端ID
    defaultTopic: default_topic   # 默认发送主题
    subTopics: test_face_queue,test_plate_queue
    cleanSession: true
    async: true
  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0

cron: 0/60 * * * * ?
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl